---
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded

- name: Restart Alloy
  ansible.builtin.service:
    name: alloy
    state: restarted
